# -*- restclient -*-

# for quick manual tests of API endpoints

:base = localhost:8082

#
GET http://:base/channels

#
GET http://:base/recordings

#
POST http://:base/epg

{
"num": 2,
"tstamp": 1670187471
}

#
POST http://:base/program

{
"num": 2,
"tstamp": 1988150400,
"duration": 100,
"title": "hello, world!"
}

#
POST http://:base/cancel

{"id": 650}
